# ── Core ──────────────────────────────────────────
CONFIG_GPIO=y
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_STDOUT_CONSOLE=y

# ── UART ──────────────────────────────────────────
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# ── CAN ───────────────────────────────────────────
CONFIG_CAN=y

# ── I2C ───────────────────────────────────────────
CONFIG_I2C=y

# ── SPI ───────────────────────────────────────────
CONFIG_SPI=y

# ── ADC ───────────────────────────────────────────
CONFIG_ADC=y

# ── Math ──────────────────────────────────────────
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

# ── Heap / Stack ──────────────────────────────────
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=4096